pageTitle = "Journal Checker Tool"
alert = "The information provided by the <em>Journal Checker Tool</em> represents cOAlition S’s current understanding in relation to the policies of the journals contained within it. We will endeavour to keep it up to date and accurate, but we do not accept any liability in relation to any errors or omissions."
address = '''
cOAlition S Office<br/>
European Science Foundation<br/>
1, quai Lezay – Marnésia<br/>
67080 Strasbourg – France
'''
licenseUrl = "https://creativecommons.org/licenses/by/4.0/"
licenseName = "Creative Commons (CC BY) Attribution 4.0 International license"
feedbackButton = "Send us feedback"
apiURL = "https://api.jct.cottagelabs.com/"
jctAssetsVersion = "2.3.2"
